# Generated by Django 6.0.6 on 2026-06-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_calls', models.IntegerField(default=0)),
                ('calls_handled_by_ai', models.IntegerField(default=0, help_text='Calls where AI resolved the query (intent != speak_to_agent)')),
                ('calls_escalated_to_human', models.IntegerField(default=0, help_text='Calls where intent == speak_to_agent or status == failed')),
                ('average_duration_seconds', models.FloatField(default=0.0, help_text='Mean call duration in seconds for the day')),
                ('top_intent', models.CharField(blank=True, help_text='Most frequently detected intent for the day', max_length=100)),
                ('accuracy_percentage', models.FloatField(default=0.0, help_text='(ai_handled / total_calls) * 100')),
            ],
            options={
                'verbose_name': 'Daily Metric',
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('week_end', models.DateField()),
                ('report_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
    ]
