# Generated by Django 6.0.6 on 2026-06-22 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='E.164 format — e.g. +254712345678', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_language', models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English')], default='sw', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, help_text='Amount the member requested in KSh', max_digits=12)),
                ('purpose', models.TextField(blank=True, help_text='What the member said they need the loan for')),
                ('preferred_repayment_period', models.IntegerField(default=12, help_text='Preferred loan term in months')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_review', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('transcript_original', models.TextField(blank=True, help_text='Full conversation transcript from the voice application call')),
                ('session_id', models.CharField(blank=True, help_text="Africa's Talking session ID for the application call", max_length=100)),
                ('caller_number', models.CharField(blank=True, help_text='Phone number used to make the application call', max_length=20)),
                ('claude_analysis', models.JSONField(blank=True, default=dict, help_text="Claude's structured extraction: {amount, purpose, period, confidence, language, notes}")),
                ('conversation_state', models.JSONField(blank=True, default=dict, help_text='Tracks which questions have been asked/answered during the voice application flow. Cleared after call completes.')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='loans.member')),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_payment_date', models.DateField(db_index=True)),
                ('due_day_of_month', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Fully Paid'), ('defaulted', 'Defaulted'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('interest_rate_annual', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.member')),
            ],
            options={
                'ordering': ['next_payment_date'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=False)),
                ('max_eligible_amount', models.DecimalField(decimal_places=2, default=0, help_text='Maximum amount the member qualifies for based on current rules', max_digits=12)),
                ('reasons', models.TextField(blank=True, help_text='Comma-separated list of pass/fail reasons')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='loans.loanapplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='loans.member')),
            ],
            options={
                'verbose_name': 'Eligibility Check',
            },
        ),
        migrations.CreateModel(
            name='MemberPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_not_disturb_start', models.TimeField(default='22:00')),
                ('do_not_disturb_end', models.TimeField(default='06:00')),
                ('max_calls_per_day', models.IntegerField(default=3)),
                ('opt_out', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='loans.member')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(db_index=True)),
                ('reminder_type', models.CharField(choices=[('pre_due', 'Pre-Due (1–3 days before)'), ('due_today', 'Due Today'), ('overdue', 'Overdue')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calling', 'Call in Progress'), ('sent', 'Call Sent / Ringing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('call_sid', models.CharField(blank=True, max_length=100)),
                ('response_received', models.TextField(blank=True)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('call_duration_seconds', models.IntegerField(default=0)),
                ('call_cost_kes', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='loans.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='loans.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('loan', 'reminder_date', 'reminder_type')},
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('call_initiated', 'Call Initiated'), ('call_answered', 'Call Answered'), ('call_no_answer', 'No Answer'), ('call_busy', 'Line Busy'), ('call_failed', 'Call Failed'), ('call_completed', 'Call Completed'), ('payment_confirmed', 'Payment Confirmed by Member'), ('payment_denied', 'Member Will Not Pay'), ('retry_scheduled', 'Retry Scheduled'), ('cancelled', 'Reminder Cancelled')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='loans.paymentreminder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('first_payment_date', models.DateField()),
                ('last_payment_date', models.DateField()),
                ('interest_rate_annual', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_plan', to='loans.loanapplication')),
            ],
            options={
                'verbose_name': 'Repayment Plan',
            },
        ),
    ]
