# Generated by Django 6.0.6 on 2026-06-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(help_text="Caller's phone number in E.164 format, e.g. +254712345678", max_length=20)),
                ('session_id', models.CharField(help_text="Africa's Talking session ID — unique per call", max_length=100, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('recording_url', models.URLField(blank=True, help_text="URL of the caller's recorded audio from Africa's Talking")),
                ('transcript', models.TextField(blank=True, help_text='Speech-to-text transcript of what the caller said')),
                ('language_detected', models.CharField(blank=True, choices=[('sw', 'Kiswahili'), ('en', 'English'), ('mixed', 'Mixed'), ('', 'Unknown')], help_text="Language detected by Claude: 'sw', 'en', or 'mixed'", max_length=10)),
                ('intent_detected', models.CharField(blank=True, help_text='Intent classified by Claude, e.g. check_balance, apply_loan, etc.', max_length=50)),
                ('response_given', models.TextField(blank=True, help_text='The text response spoken back to the caller via TTS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Call duration in seconds (populated after call ends)')),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
